### ISSUE TITLE
enabling HTTPS for the API end point

### ISSUE THREAD

**Issue by koushik9951** [ExpediaGroup/pitchfork#244] opened 2020-06-16 16:48 UTC
I am trying to enable HTTPS (ssl), but it's failing , is their any functionality  to enable it?

**Comment by koushik9951** [comment] 2020-06-17 06:02
@worldtiki : Thanks for your response ,i am want enable  HTTPS(by passing a certs) PITCHFORK itslef , so that Pitchfork API us as HTTPS

**Comment by koushik9951** [comment] 2020-06-17 06:35
this is what i tried to enable HTTPS by adding below properties in **application.yml ** file , but I am getting **certificate unkown** exception  while posting traces 
server:
  port: 9411
  ssl:
      key-store-password: changeit
      key-store: ssl-server.jks
      key-password: changeit
      key-store-type: JKS
      enabled: true
security:
  require-ssl: true

**Comment by worldtiki** [comment] 2020-06-17 09:10
That looks ok.

I tried to reproduce the error and couldn't. I pushed a branch to my fork here, with a self-signed cert: https://github.com/worldtiki/pitchfork/blob/ssl_test/src/main/resources/application.yml#L6-L11

(I don't have the require-ssl because I didn't add spring security).

Do you mind trying this branch?
I wonder if the issue is with the location of your jks file.

**Comment by worldtiki** [comment] 2021-01-20 15:19
@koushik9951 I'm going to close this issue. If you need help just comment and I'll reopen it.

**Closed by worldtiki** 2021-01-20 15:19 UTC
